return {
	bashls = {},
	cssls = {},
	docker_compose_language_service = {},
	dockerls = {},
	eslint = require("epinero.lsp.servers.eslint"),
	gopls = require("epinero.lsp.servers.gopls"),
	html = {},
	jsonls = require("epinero.lsp.servers.jsonls"),
	lua_ls = require("epinero.lsp.servers.lua_ls"),
	roslyn_ls = require("epinero.lsp.servers.roslyn_ls"),
	sqlls = {},
	ts_ls = require("epinero.lsp.servers.ts_ls"),
	yamlls = require("epinero.lsp.servers.yamlls"),
}
